### ISSUE TITLE
pubnubStream.js file

### ISSUE THREAD

**Issue by GhaidaMK** [initialstate/pubnub-live-twitter-dashboard#2]
Hi,
This isn't an issue it's more of a question, I read your explanation of your code which was well explained btw 👍 
But what's the purpose of pubnubStream.js file? Can I rely only on the twitterTest.js file? Or do I need to use my subscribe key and publish key? Because when I run the file nothing changes nor do I notice a difference in the results.
I'm working on project that is very similar to yours and I'm using PubNub too :)

**Comment by RChloe** [comment]
Hi!
The only difference between the two scripts is the sending for Sentiment Analysis through the IBM block which then gets routed through the Initial State block. The pubnubStream.js file takes some of the sentiment analysis output and reformats it for Initial State. 
If you are just looking to filter through Twitter feeds, twitterTest.js will work just fine without you needing to add any key - it uses a PubNub public key.
If you want to route those tweets back through any PubNub blocks on your PubNub account, you'll need to add your publish key and follow the format of the pubnubStream.js file.
Hope that answers your question!
